<li>They are the UKs biggest earners</li>
<li>They score highest for social, cultural and economic factors</li>
<li>Many went to private school and elite universities – 24% of people in this group were privately educated – far more than in any other class group</li>
<li>This class is most likely to be found in London and the home counties</li>
<li>This group is exclusive and very hard to join – most come from very privileged backgrounds</li>
<li>97% of people in this group own their own home</li>