<li>These people have the youngest average age</li>
<li>They have the highest score for emerging culture activity, which includes, going to gigs, using Facebook/Twitter and playing sport</li>
<li>They are an urban group, living in cheap locations in large cities like Liverpool and Newcastle</li>
<li>They socialise with a broad range of people</li>
<li>They’re likely to come from working class backgrounds</li>