<li>This youthful class group is economically secure, without being well off</li>
<li>These people have high scores for emerging culture, such as watching sport, going to gigs and using Facebook and Twitter</li>
<li>They don’t tend to participate in highbrow culture, such as classical music and theatre</li>
<li>People in this group are more likely to come from a working class background</li>
<li>Many people in this group live in old manufacturing centres of the UK in the Midlands and North West</li>