<div id="gbcs-CharacterNavView" class="CharacterNavView is-hidden">

    <ul>
        <li id="CharacterNavView-user" class="is-active">
            <a href="#gbcs-ArchetypesView-user">
                <i class="character-nav character-nav-user"></i>
                <span>You</span>
            </a>
        </li>
        <li id="CharacterNavView-elite">
            <a href="#gbcs-ArchetypesView-elite">
                <i class="character-nav character-nav-elite"></i>
                <span>Elite</span>
            </a>
        </li>
        <li id="CharacterNavView-established-middle">
            <a href="#gbcs-ArchetypesView-established-middle">
                <i class="character-nav character-nav-established-middle"></i>
                <span>Established middle class</span>
            </a>
        </li>
        <li id="CharacterNavView-technical-middle">
            <a href="#gbcs-ArchetypesView-technical-middle">
                <i class="character-nav character-nav-technical-middle"></i>
                <span>Technical middle class</span>
            </a>
        </li>
        <li id="CharacterNavView-affluent-worker">
            <a href="#gbcs-ArchetypesView-affluent-worker">
                <i class="character-nav character-nav-affluent-worker"></i>
                <span>New affluent workers</span>
            </a>
        </li>
        <li id="CharacterNavView-traditional-worker">
            <a href="#gbcs-ArchetypesView-traditional-worker">
                <i class="character-nav character-nav-traditional-worker"></i>
                <span>Traditional working class</span>
            </a>
        </li>
        <li id="CharacterNavView-emergent-worker">
            <a href="#gbcs-ArchetypesView-emergent-worker">
                <i class="character-nav character-nav-emergent-worker"></i>
                <span>Emergent service workers</span>
            </a>
        </li>
        <li id="CharacterNavView-precariat">
            <a href="#gbcs-ArchetypesView-precariat">
                <i class="character-nav character-nav-precariat"></i>
                <span>Precariat</span>
            </a>
        </li>
    </ul>

    <div class="CharacterNavView-nav">
        <button class="next">Next<i class="sprite sprite-icon-next"></i></button>
        <button class="prev">Prev<i class="sprite sprite-icon-prev"></i></button>
    </div>

</div>