<div id="gbcs-ProgressView" class="ProgressView is-hidden">

    <ol>
        <li id="ProgressView-economic">
            <span>Economic<i class="sprite sprite-icon-economic"></i></span>
        </li>
        <li id="ProgressView-social">
            <span>Social<i class="sprite sprite-icon-social"></i></span>
        </li>
        <li id="ProgressView-cultural">
            <span>Cultural<i class="sprite sprite-icon-cultural"></i></span>
        </li>
        <li id="ProgressView-result" class="last-child">
            <span>Your result<i class="sprite sprite-icon-result"></i></span>
        </li>
    </ol>

</div>