<form class="is-hidden" tabindex="-1" autocomplete="off">

    <h3 class="visuallyhidden">Social</h3>

    <fieldset data-ui="checkboxes" class="last-child">
        <legend class="h2"><%= include('question-social-people.inc') %></legend>
        <input type="hidden" name="social" value="0">
        <div class="clearfix">
            <div class="QuestionsView-column">
                <label for="social-secretary" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-secretary" name="social" value="47.49">
                    Secretary
                </label>
                <label for="social-nurse" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-nurse" name="social" value="36.78">
                    Nurse
                </label>
                <label for="social-teacher" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-teacher" name="social" value="76.46">
                    Teacher
                </label>
                <label for="social-cleaner" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-cleaner" name="social" value="10.73">
                    Cleaner
                </label>
                <label for="social-university-lecturer" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-university-lecturer" name="social" value="85.30">
                    University lecturer
                </label>
                <label for="social-artist" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-artist" name="social" value="42.95">
                    Artist
                </label>
                <label for="social-electrician" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-electrician" name="social" value="24.44">
                    Electrician
                </label>
                <label for="social-office-manager" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-office-manager" name="social" value="59.30">
                    Office manager
                </label>
                <label for="social-solicitor" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-solicitor" name="social" value="75.12">
                    Solicitor
                </label>
            </div>
            <div class="QuestionsView-column">
                <label for="social-farm-worker" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-farm-worker" name="social" value="14.17">
                    Farm worker
                </label>
                <label for="social-chief-executive" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-chief-executive" name="social" value="70.82">
                    Chief executive
                </label>
                <label for="social-software-designer" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-software-designer" name="social" value="51.48">
                    Software designer
                </label>
                <label for="social-call-centre-worker" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-call-centre-worker" name="social" value="27.96">
                    Call centre worker
                </label>
                <label for="social-postal-worker" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-postal-worker" name="social" value="23.06">
                    Postal worker
                </label>
                <label for="social-scientist" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-scientist" name="social" value="68.77">
                    Scientist
                </label>
                <label for="social-lorry-driver" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-lorry-driver" name="social" value="14.50">
                    Lorry driver
                </label>
                <label for="social-accountant" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-accountant" name="social" value="57.50">
                    Accountant
                </label>
                <label for="social-shop-assistant" class="for-checkbox">
                    <i class="sprite"></i>
                    <input type="checkbox" id="social-shop-assistant" name="social" value="31.32">
                    Shop assistant
                </label>
            </div>
        </div>
    </fieldset>

    <div class="QuestionsView-nav">
        <button type="submit">Next<i class="sprite sprite-icon-next"></i></button>
        <button class="prev" type="button">Prev<i class="sprite sprite-icon-prev"></i></button>
    </div>

</form>