<div class="ResultsView-archetypes">

    <h2 class="visuallyhidden">Archetypes</h2>

    <ul>
        <li id="gbcs-ResultsView-elite" class="ResultsView-item" tabindex="-1">
            <h3 class="h1">Elite</h3>
            <div class="ResultsView-item-stats">
                <p>
                    <span class="ResultsView-item-stats-title">Percentage of population</span>
                    <span class="ResultsView-item-stats-value">
                        <i class="piechart piechart-6pc"></i>
                        6%
                    </span>
                </p>
                <p>
                    <span class="ResultsView-item-stats-title">Average age</span>
                    <span class="ResultsView-item-stats-value">57</span>
                </p>
            </div>
            <p><%= include('archetype-elite-intro.inc') %></p>
            <ul>
            <%= include('archetype-elite.inc') %>
            </ul>
        </li>
        <li id="gbcs-ResultsView-established-middle" class="ResultsView-item" tabindex="-1">
            <h3 class="h1">Established middle class</h3>
            <div class="ResultsView-item-stats">
                <p>
                    <span class="ResultsView-item-stats-title">Percentage of population</span>
                    <span class="ResultsView-item-stats-value">
                        <i class="piechart piechart-25pc"></i>
                        25%
                    </span>
                </p>
                <p>
                    <span class="ResultsView-item-stats-title">Average age</span>
                    <span class="ResultsView-item-stats-value">46</span>
                </p>
            </div>
            <p><%= include('archetype-established-middle-intro.inc') %></p>
            <ul>
            <%= include('archetype-established-middle.inc') %>
            </ul>
        </li>
        <li id="gbcs-ResultsView-technical-middle" class="ResultsView-item" tabindex="-1">
            <h3 class="h1">Technical middle class</h3>
            <div class="ResultsView-item-stats">
                <p>
                    <span class="ResultsView-item-stats-title">Percentage of population</span>
                    <span class="ResultsView-item-stats-value">
                        <i class="piechart piechart-6pc"></i>
                        6%
                    </span>
                </p>
                <p>
                    <span class="ResultsView-item-stats-title">Average age</span>
                    <span class="ResultsView-item-stats-value">52</span>
                </p>
            </div>
            <p> <%= include('archetype-technical-middle-intro.inc') %></p>
            <ul>
            <%= include('archetype-technical-middle.inc') %>
            </ul>
        </li>
        <li id="gbcs-ResultsView-affluent-worker" class="ResultsView-item" tabindex="-1">
            <h3 class="h1">New affluent workers</h3>
            <div class="ResultsView-item-stats">
                <p>
                    <span class="ResultsView-item-stats-title">Percentage of population</span>
                    <span class="ResultsView-item-stats-value">
                        <i class="piechart piechart-15pc"></i>
                        15%
                    </span>
                </p>
                <p>
                    <span class="ResultsView-item-stats-title">Average age</span>
                    <span class="ResultsView-item-stats-value">44</span>
                </p>
            </div>
            <p><%= include('archetype-affluent-workers-intro.inc') %></p>
            <ul>
            <%= include('archetype-affluent-workers.inc') %>
            </ul>
        </li>
        <li id="gbcs-ResultsView-traditional-worker" class="ResultsView-item" tabindex="-1">
            <h3 class="h1">Traditional working class</h3>
            <div class="ResultsView-item-stats">
                <p>
                    <span class="ResultsView-item-stats-title">Percentage of population</span>
                    <span class="ResultsView-item-stats-value">
                        <i class="piechart piechart-14pc"></i>
                        14%
                    </span>
                </p>
                <p>
                    <span class="ResultsView-item-stats-title">Average age</span>
                    <span class="ResultsView-item-stats-value">66</span>
                </p>
            </div>
            <p> <%= include('archetype-traditional-workers-intro.inc') %></p>
            <ul>
            <%= include('archetype-traditional-workers.inc') %>
            </ul>
        </li>
        <li id="gbcs-ResultsView-emergent-worker" class="ResultsView-item" tabindex="-1">
            <h3 class="h1">Emergent service workers</h3>
            <div class="ResultsView-item-stats">
                <p>
                    <span class="ResultsView-item-stats-title">Percentage of population</span>
                    <span class="ResultsView-item-stats-value">
                        <i class="piechart piechart-19pc"></i>
                        19%
                    </span>
                </p>
                <p>
                    <span class="ResultsView-item-stats-title">Average age</span>
                    <span class="ResultsView-item-stats-value">34</span>
                </p>
            </div>
            <p><%= include('archetype-emergent-workers-intro.inc') %></p>
            <ul>
            <%= include('archetype-emergent-workers.inc') %>
            </ul>
        </li>
        <li id="gbcs-ResultsView-precariat" class="ResultsView-item" tabindex="-1">
            <h3 class="h1">Precariat</h3>
            <div class="ResultsView-item-stats">
                <p>
                    <span class="ResultsView-item-stats-title">Percentage of population</span>
                    <span class="ResultsView-item-stats-value">
                        <i class="piechart piechart-15pc"></i>
                        15%
                    </span>
                </p>
                <p>
                    <span class="ResultsView-item-stats-title">Average age</span>
                    <span class="ResultsView-item-stats-value">50</span>
                </p>
            </div>
            <p> <%= include('archetype-precariat-intro.inc') %></p>
            <ul>
            <%= include('archetype-precariat.inc') %>
            </ul>
        </li>
    </ul>

</div>