<div class="ResultsView-summaries">

    <div id="gbcs-ResultsView-summary-elite" class="ResultsView-summary">
        <h4 class="h1">Elite</h4>
        <p><%= include('summary-intro-elite.inc') %></p>
        <ul>
        <%= include('summary-elite.inc') %>
        </ul>
    </div>
    <div id="gbcs-ResultsView-summary-established-middle" class="ResultsView-summary">
        <h4 class="h1">Established middle class</h4>
        <p><%= include('summary-intro-established-middle.inc') %></p>
        <ul>        
        <%= include('summary-established-middle.inc') %>
        </ul>  
    </div>
    <div id="gbcs-ResultsView-summary-technical-middle" class="ResultsView-summary">
        <h4 class="h1">Technical middle class</h4>
        <p> <%= include('summary-intro-technical-middle.inc') %></p>
        <ul>        
        <%= include('summary-technical-middle.inc') %>
        </ul>    
    </div>
    <div id="gbcs-ResultsView-summary-affluent-worker" class="ResultsView-summary">
        <h4 class="h1">New affluent workers</h4>
        <p><%= include('summary-intro-affluent-workers.inc') %></p>
        <ul>        
        <%= include('summary-affluent-workers.inc') %>
        </ul>    
    </div>
    <div id="gbcs-ResultsView-summary-traditional-worker" class="ResultsView-summary">
        <h4 class="h1">Traditional working class</h4>
        <p><%= include('summary-intro-traditional-workers.inc') %></p>
        <ul>        
        <%= include('summary-traditional-workers.inc') %>
        </ul>        
    </div>
    <div id="gbcs-ResultsView-summary-emergent-worker" class="ResultsView-summary">
        <h4 class="h1">Emergent service workers</h4>
        <p><%= include('summary-intro-emergent-workers.inc') %></p>
        <ul>        
        <%= include('summary-emergent-workers.inc') %>
        </ul>    
    </div>
    <div id="gbcs-ResultsView-summary-precariat" class="ResultsView-summary">
        <h4 class="h1">Precariat</h4>
        <p><%= include('summary-intro-precariat.inc') %></p>
        <ul>        
        <%= include('summary-precariat.inc') %>
        </ul>
    </div>

</div>