<div id="gbcs-SplashView" class="SplashView">
    <div class="SplashView-body">
        <h2 class="h1">Take the test</h2>
        <p>The results from BBC Lab UK’s Great British Class Survey reveal a brand new class system of seven groups.</p>
        <p>Answer five questions to see where you fit:</p>
        <div class="SplashView-nav">
            <a href="#gbcs-QuestionsView">Tell us about you</a>
        </div>
        <div class="SplashView-characters">
            <i class="characters-small characters-small-elite"></i>
            <i class="characters-small characters-small-established-middle"></i>
            <i class="characters-small characters-small-technical-middle"></i>
            <i class="characters-small characters-small-affluent-worker"></i>
            <i class="characters-small characters-small-traditional-worker"></i>
            <i class="characters-small characters-small-emergent-worker"></i>
            <i class="characters-small characters-small-precariat"></i>
        </div>
    </div>
</div>